dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master
    - develop

before_script:
  - env | sort
  - name="powerdns"
  - image="docker-powerdns"
  - dir="."

script:
  - travis_retry docker build -t "$image" "$dir"
  - docker images
  - docker run --name "$name" -e AUTOCONF=$AUTOCONF -d "$image" "$dir"
  - docker ps | grep "$name"
  - docker logs "$name"

notifications:
  email: false

env: # Environments
    - AUTOCONF=false
    - AUTOCONF=sqlite
