os: linux
dist: bionic

services: docker

language: shell

branches:
  only:
    - master
    - develop

before_install:
  - env | sort
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export CONTAINER_NAME="pdns-server"
  - export TAG=travis
  - export IMAGE_NAME="docker-powerdns:${TAG}"
  - export home=$(pwd)
  - export travis_dir="${home}/"

install:
  - cd "$travis_dir"
  # Test container build
  - travis_retry docker build -t "${IMAGE_NAME}" "$travis_dir"

before_script:
  - docker images

script:
  - cd "$travis_dir"
  # Test container run
  - docker run --rm --name "cmd_help" -e AUTOCONF=$AUTOCONF "${IMAGE_NAME}" --help
  #- docker run --rm --name "cmd_version" -e AUTOCONF=$AUTOCONF "${IMAGE_NAME}" --version
  - docker run --name "${CONTAINER_NAME}" -e AUTOCONF=$AUTOCONF -d "${IMAGE_NAME}"
  - docker ps | grep "${CONTAINER_NAME}"
  - docker logs "${CONTAINER_NAME}"
  - docker stop "${CONTAINER_NAME}" && docker rm -f "${CONTAINER_NAME}"
  # Docker-compose tests
  - mv docker-compose.$AUTOCONF.test.yml docker-compose.yml
  - rm -f docker-compose_*.yml
  - travis_retry travis_wait 60 docker-compose build
  - docker images
  - travis_retry docker-compose up -d && sleep 30
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "${CONTAINER_NAME}" | grep "Up"
  - echo 'Wait until everything ready (1-2 minutes)' && sleep 120
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "${CONTAINER_NAME}" | grep "Up"
  - docker-compose down
  - travis_retry docker-compose up -d && sleep 30
  - echo 'Wait until everything ready (1-2 minutes)' && sleep 120
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "${CONTAINER_NAME}" | grep "Up"

notifications:
  email: false

env: # Environments
    #- AUTOCONF=false
    #- AUTOCONF=sqlite
    #- AUTOCONF=postgres
    - AUTOCONF=mysql
