dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master
    - develop

before_script:
  - env | sort
  - name="powerdns"
  - image="docker-powerdns"
  - dir="."

script:
  - travis_retry docker build -t "$image" "$dir"
  - docker images
  - docker run --name "$name" -d "$image" "$dir" -e BACKEND=$BACKEND -e MYSQL_AUTOCONF=$MYSQL_AUTOCONF -e PGSQL_AUTOCONF=$PGSQL_AUTOCONF -e SQLITE_AUTOCONF=$SQLITE_AUTOCONF
  - docker ps | grep "$name"
  - docker logs "$name"

notifications:
  email: false

env: # Environments
    - BACKEND=bind MYSQL_AUTOCONF=false PGSQL_AUTOCONF=false SQLITE_AUTOCONF=false
    - BACKEND=sqlite MYSQL_AUTOCONF=false PGSQL_AUTOCONF=false SQLITE_AUTOCONF=true
